<?php
return array(
	'qq' => array(
		'status'=> '1',
		'from'	=> 'qq',
		'show'	=> '腾讯视频',
		'des'	=> '腾讯视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '01',
		'tip'	=> '在线播放',
	),
	'youku' => array(
		'status'=> '1',
		'from'	=> 'youku',
		'show'	=> '优酷视频',
		'des'	=> '优酷视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '02',
		'tip'	=> '在线播放',
	),
	'sohu' => array(
		'status'=> '1',
		'from'	=> 'sohu',
		'show'	=> '搜狐视频',
		'des'	=> '搜狐视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '03',
		'tip'	=> '在线播放',
	),
	'qiyi' => array(
		'status'=> '1',
		'from'	=> 'qiyi',
		'show'	=> '奇艺视频',
		'des'	=> '奇艺视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '04',
		'tip'	=> '在线播放',
	),
	'pptv' => array(
		'status'=> '1',
		'from'	=> 'pptv',
		'show'	=> 'PP视频',
		'des'	=> 'PP视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '05',
		'tip'	=> '在线播放',
	),
	'mgtv' => array(
		'status'=> '1',
		'from'	=> 'mgtv',
		'show'	=> '芒果TV',
		'des'	=> '芒果TV',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '06',
		'tip'	=> '在线播放',
	),
	'letv' => array(
		'status'=> '1',
		'from'	=> 'letv',
		'show'	=> '乐视视频',
		'des'	=> '乐视视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '07',
		'tip'	=> '在线播放',
	),
	'cntv' => array(
		'status'=> '1',
		'from'	=> 'cntv',
		'show'	=> '央视视频',
		'des'	=> '央视视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '08',
		'tip'	=> '在线播放',
	),
	'wasu' => array(
		'status'=> '1',
		'from'	=> 'wasu',
		'show'	=> '华数视频',
		'des'	=> '华数视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '09',
		'tip'	=> '在线播放',
	),
	'kankan' => array(
		'status'=> '1',
		'from'	=> 'kankan',
		'show'	=> '迅雷看看',
		'des'	=> '迅雷看看',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '10',
		'tip'	=> '在线播放',
	),
	'funshion' => array(
		'status'=> '1',
		'from'	=> 'funshion',
		'show'	=> '风行视频',
		'des'	=> '风行视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '11',
		'tip'	=> '在线播放',
	),
	'tudou' => array(
		'status'=> '1',
		'from'	=> 'tudou',
		'show'	=> '土豆视频',
		'des'	=> '土豆视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '12',
		'tip'	=> '在线播放',
	),
	'1905' => array(
		'status'=> '1',
		'from'	=> '1905',
		'show'	=> 'M1905',
		'des'	=> 'M1905',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '13',
		'tip'	=> '在线播放',
	),
	'miaopai' => array (
		'status'=> '1',
		'from'	=> 'miaopai',
		'show'	=> '秒拍视频',
		'des'	=> '秒拍视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '14',
		'tip'	=> '在线播放',
	),
	'yyshenqu' => array (
		'status'=> '1',
		'from'	=> 'yyshenqu',
		'show'	=> 'YY神曲',
		'des'	=> 'YY神曲',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '15',
		'tip'	=> '在线播放',
	),
	'vlook' => array (
	    'status'=> '1',
	    'from'	=> 'vlook',
	    'show'	=> '微录客',
	    'des'	=> '微录客',
	    'ps'	=> '1',
	    'parse' => '/template/vfed/asset/fed/player.php?url=',
	    'sort'	=> '16',
	    'tip'	=> '在线播放',
	),
	'bilibili' => array(
		'status'=> '1',
		'from'	=> 'bilibili',
		'show'	=> '哔哩哔哩',
		'des'	=> '哔哩哔哩',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '17',
		'tip'	=> '在线播放',
	),
	'yytai' => array(
		'status'=> '1',
		'from'	=> 'yytai',
		'show'	=> '音悦台',
		'des'	=> '音悦台',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '18',
		'tip'	=> '在线播放',
	),
	'm3u8' => array(
		'status'=> '1',
		'from'	=> 'm3u8',
		'show'	=> '切片视频',
		'des'	=> '切片视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '19',
		'tip'	=> '在线播放',
	),
	'live' => array(
		'status'=> '1',
		'from'	=> 'live',
		'show'	=> '本地直播',
		'des'	=> '本地直播专用,不能跨域,支持连播下一集',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?id=13&url=',
		'sort'	=> '20',
		'tip'	=> '在线直播',
	),
	'html' => array(
		'status'=> '1',
		'from'	=> 'html',
		'show'	=> '本地播放',
		'des'	=> 'CK播放器,支持连播下一集',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?id=14&url=',
		'sort'	=> '21',
		'tip'	=> '在线播放',
	),
	'play' => array(
		'status'=> '1',
		'from'	=> 'play',
		'show'	=> '本地播放',
		'des'	=> 'DP播放器,支持连播下一集',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?id=15&url=',
		'sort'	=> '22',
		'tip'	=> '在线播放',
	),
	'ckplayer' => array(
		'status'=> '1',
		'from'	=> 'ckplayer',
		'show'	=> 'CK云播',
		'des'	=> 'CK云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '23',
		'tip'	=> '在线播放',
	),
	'27pan' => array(
		'status'=> '1',
		'from'	=> '27pan',
		'show'	=> '27盘视频',
		'des'	=> '27盘视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '24',
		'tip'	=> '在线播放',
	),
	'zuidall' => array(
		'status'=> '1',
		'from'	=> 'zuidall',
		'show'	=> '最大云播',
		'des'	=> '最大云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '25',
		'tip'	=> '在线播放',
	),
	'zuidam3u8' => array(
		'status'=> '1',
		'from'	=> 'zuidam3u8',
		'show'	=> '最大M3U8',
		'des'	=> '最大M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '26',
		'tip'	=> '在线播放',
	),
	'xinyun' => array(
		'status'=> '1',
		'from'	=> 'xinyun',
		'show'	=> '最新云播',
		'des'	=> '最新云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '27',
		'tip'	=> '在线播放',
	),
	'xinm3u8' => array(
		'status'=> '1',
		'from'	=> 'xinm3u8',
		'show'	=> '最新M3U8',
		'des'	=> '最新M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '28',
		'tip'	=> '在线播放',
	),
	'zkyun' => array(
		'status'=> '1',
		'from'	=> 'zkyun',
		'show'	=> '最快云播',
		'des'	=> '最快云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '29',
		'tip'	=> '在线播放',
	),
	'zkm3u8' => array(
		'status'=> '1',
		'from'	=> 'zkm3u8',
		'show'	=> '最快M3U8',
		'des'	=> '最快M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '30',
		'tip'	=> '在线播放',
	),
	'bwyun' => array(
		'status'=> '1',
		'from'	=> 'bwyun',
		'show'	=> '百万云播',
		'des'	=> '百万云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '31',
		'tip'	=> '在线播放',
	),
	'bwm3u8' => array(
		'status'=> '1',
		'from'	=> 'bwm3u8',
		'show'	=> '百万M3U8',
		'des'	=> '百万M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '32',
		'tip'	=> '在线播放',
	),
	'jsyun' => array(
		'status'=> '1',
		'from'	=> 'jsyun',
		'show'	=> '急速云播',
		'des'	=> '急速云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '33',
		'tip'	=> '在线播放',
	),
	'jsm3u8' => array(
		'status'=> '1',
		'from'	=> 'jsm3u8',
		'show'	=> '急速M3U8',
		'des'	=> '急速M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '34',
		'tip'	=> '在线播放',
	),
	'yjyun' => array(
		'status'=> '1',
		'from'	=> 'yjyun',
		'show'	=> '永久云播',
		'des'	=> '永久云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '35',
		'tip'	=> '在线播放',
	),
	'yjm3u8' => array(
		'status'=> '1',
		'from'	=> 'yjm3u8',
		'show'	=> '永久M3U8',
		'des'	=> '永久M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '36',
		'tip'	=> '在线播放',
	),
	'jpyun' => array (
		'status'=> '1',
		'from'	=> 'jpyun',
		'show'	=> '精品云播',
		'des'	=> '精品云播',
		'ps'	=> '1',
		'parse' => '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '37',
		'tip'	=> '在线播放',
	),
	'jpm3u8' => array(
		'status'=> '1',
		'from'	=> 'jpm3u8',
		'show'	=> '精品资源',
		'des'	=> '精品资源',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '38',
		'tip'	=> '在线播放',
	),
	'kuyun' => array(
		'status'=> '1',
		'from'	=> 'kuyun',
		'show'	=> '酷云视频',
		'des'	=> '酷云视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '39',
		'tip'	=> '在线播放',
	),
	'ckm3u8' => array(
		'status'=> '1',
		'from'	=> 'ckm3u8',
		'show'	=> '酷云M3U8',
		'des'	=> '酷云M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '40',
		'tip'	=> '在线播放',
	),
	'kkyun' => array(
		'status'=> '1',
		'from'	=> 'kkyun',
		'show'	=> '酷酷云播',
		'des'	=> '酷酷云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '41',
		'tip'	=> '在线播放',
	),
	'kkm3u8' => array(
		'status'=> '1',
		'from'	=> 'kkm3u8',
		'show'	=> '酷酷M3U8',
		'des'	=> '酷酷M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '42',
		'tip'	=> '在线播放',
	),
	'33uu' => array(
		'status'=> '1',
		'from'	=> '33uu',
		'show'	=> '33UU视频',
		'des'	=> '33UU视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '43',
		'tip'	=> '在线播放',
	),
	'33uuck' => array(
		'status'=> '1',
		'from'	=> '33uuck',
		'show'	=> '33UUM3U8',
		'des'	=> '33UUM3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '44',
		'tip'	=> '在线播放',
	),
	'131zy' => array(
		'status'=> '1',
		'from'	=> '131zy',
		'show'	=> '131云播',
		'des'	=> '131云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '45',
		'tip'	=> '在线播放',
	),
	'131m3u8' => array(
		'status'=> '1',
		'from'	=> '131m3u8',
		'show'	=> '131M3U8',
		'des'	=> '131M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '46',
		'tip'	=> '在线播放',
	),
	'link' => array(
		'status'=> '1',
		'from'	=> 'link',
		'show'	=> '1977视频',
		'des'	=> '1977视频',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '47',
		'tip'	=> '在线播放',
	),
	'gom3u8' => array(
		'status'=> '1',
		'from'	=> 'gom3u8',
		'show'	=> '1977M3U8',
		'des'	=> '1977M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '48',
		'tip'	=> '在线播放',
	),
	'605yun' => array(
		'status'=> '1',
		'from'	=> '605yun',
		'show'	=> '605云播',
		'des'	=> '605云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '49',
		'tip'	=> '在线播放',
	),
	'605m3u8' => array(
		'status'=> '1',
		'from'	=> '605m3u8',
		'show'	=> '605M3U8',
		'des'	=> '605M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '50',
		'tip'	=> '在线播放',
	),
	'129zy' => array(
		'status'=> '1',
		'from'	=> '129zy',
		'show'	=> '129云播',
		'des'	=> '129云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '51',
		'tip'	=> '在线播放',
	),
	'129m3u8' => array(
		'status'=> '1',
		'from'	=> '129m3u8',
		'show'	=> '129M3U8',
		'des'	=> '129M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '52',
		'tip'	=> '在线播放',
	),
	'kakam3u8'	=> array(
		'status'=> '1',
		'from'	=> 'kakam3u8',
		'show'	=> '酷播M3U8',
		'des'	=> '酷播M3U8',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '53',
		'tip'	=> '在线播放',
	),
	'8laoye' => array(
		'status'=> '1',
		'from'	=> '8laoye',
		'show'	=> '老爷云播',
		'des'	=> '老爷云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '54',
		'tip'	=> '在线播放',
	),
	'yzm' => array(
		'status'=> '1',
		'from'	=> 'yzm',
		'show'	=> 'C值云播',
		'des'	=> 'C值云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '55',
		'tip'	=> '在线播放',
	),
	'qsv' => array(
		'status'=> '1',
		'from'	=> 'qsv',
		'show'	=> '哥搞妹',
		'des'	=> '哥搞妹',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '56',
		'tip'	=> '在线播放',
	),
	'ixx' => array(
		'status'=> '1',
		'from'	=> 'ixx',
		'show'	=> 'IXX云播',
		'des'	=> 'IXX云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '57',
		'tip'	=> '在线播放',
	),
	'9zav' => array(
		'status'=> '1',
		'from'	=> '9zav',
		'show'	=> '九州云播',
		'des'	=> '九州云播',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '58',
		'tip'	=> '在线播放',
	),
	'bt616' => array(
		'status'=> '1',
		'from'	=> 'bt616',
		'show'	=> 'BT616',
		'des'	=> 'BT616',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '59',
		'tip'	=> '在线播放',
	),
	'ckyun' => array (
		'status'=> '1',
		'from'	=> 'ckyun',
		'show'	=> '云高清',
		'des'	=> '云高清',
		'ps'	=> '1',
		'parse'	=> '/template/vfed/asset/fed/player.php?url=',
		'sort'	=> '60',
		'tip'	=> '在线播放',
	),
);
?>