/*
 SeaJS - A Module Loader for the Web
 v1.2.1 | seajs.org | MIT Licensed
*/
window.seajs||(this.seajs={_seajs:this.seajs},seajs.version="1.2.1",seajs._util={},seajs._config={debug:"%DEBUG%",preload:[]},function(a){var b=Object.prototype.toString,e=Array.prototype;a.isString=function(a){return"[object String]"===b.call(a)};a.isFunction=function(a){return"[object Function]"===b.call(a)};a.isRegExp=function(a){return"[object RegExp]"===b.call(a)};a.isObject=function(a){return a===Object(a)};a.isArray=Array.isArray||function(a){return"[object Array]"===b.call(a)};a.indexOf=e.indexOf?
function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1};var c=a.forEach=e.forEach?function(a,b){a.forEach(b)}:function(a,b){for(var c=0;c<a.length;c++)b(a[c],c,a)};a.map=e.map?function(a,b){return a.map(b)}:function(a,b){var d=[];c(a,function(a,c,e){d.push(b(a,c,e))});return d};a.filter=e.filter?function(a,b){return a.filter(b)}:function(a,b){var d=[];c(a,function(a,c,e){b(a,c,e)&&d.push(a)});return d};var d=a.keys=Object.keys||function(a){var b=
[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b};a.unique=function(a){var b={};c(a,function(a){b[a]=1});return d(b)};a.now=Date.now||function(){return(new Date).getTime()}}(seajs._util),function(a,b){var e=Array.prototype;a.log=function(){if("undefined"!==typeof console){var a=e.slice.call(arguments),d="log";console[a[a.length-1]]&&(d=a.pop());if("log"!==d||b.debug)a="dir"===d?a[0]:e.join.call(a," "),console[d](a)}}}(seajs._util,seajs._config),function(a,b,e){function c(a){a=a.match(o);return(a?
a[0]:".")+"/"}function d(a){f.lastIndex=0;f.test(a)&&(a=a.replace(f,"$1/"));if(-1===a.indexOf("."))return a;for(var b=a.split("/"),c=[],d,e=0;e<b.length;e++)if(d=b[e],".."===d){if(0===c.length)throw Error("The path is invalid: "+a);c.pop()}else"."!==d&&c.push(d);return c.join("/")}function l(a){var a=d(a),b=a.charAt(a.length-1);if("/"===b)return a;"#"===b?a=a.slice(0,-1):-1===a.indexOf("?")&&!h.test(a)&&(a+=".js");0<a.indexOf(":80/")&&(a=a.replace(":80/","/"));return a}function n(a){if("#"===a.charAt(0))return a.substring(1);
var c=b.alias;if(c&&p(a)){var f=a.split("/"),d=f[0];c.hasOwnProperty(d)&&(f[0]=c[d],a=f.join("/"))}return a}function k(a){return 0<a.indexOf("://")||0===a.indexOf("//")}function g(a){return"/"===a.charAt(0)&&"/"!==a.charAt(1)}function p(a){var b=a.charAt(0);return-1===a.indexOf("://")&&"."!==b&&"/"!==b}var o=/.*(?=\/.*$)/,f=/([^:\/])\/\/+/g,h=/\.(?:css|js)$/,j=/^(.*?\w)(?:\/|$)/,i={},e=e.location,q=e.protocol+"//"+e.host+function(a){"/"!==a.charAt(0)&&(a="/"+a);return a}(e.pathname);0<q.indexOf("\\")&&
(q=q.replace(/\\/g,"/"));a.dirname=c;a.realpath=d;a.normalize=l;a.parseAlias=n;a.parseMap=function(c){var f=b.map||[];if(!f.length)return c;for(var d=c,e=0;e<f.length;e++){var g=f[e];if(a.isArray(g)&&2===g.length){var j=g[0];if(a.isString(j)&&-1<d.indexOf(j)||a.isRegExp(j)&&j.test(d))d=d.replace(j,g[1])}else a.isFunction(g)&&(d=g(d))}d!==c&&(i[d]=c);return d};a.unParseMap=function(a){return i[a]||a};a.id2Uri=function(a,d){if(!a)return"";a=n(a);d||(d=q);var f;k(a)?f=a:0===a.indexOf("./")||0===a.indexOf("../")?
(0===a.indexOf("./")&&(a=a.substring(2)),f=c(d)+a):f=g(a)?d.match(j)[1]+a:b.base+"/"+a;return l(f)};a.isAbsolute=k;a.isRoot=g;a.isTopLevel=p;a.pageUri=q}(seajs._util,seajs._config,this),function(a,b){function e(a,c){a.onload=a.onerror=a.onreadystatechange=function(){o.test(a.readyState)&&(a.onload=a.onerror=a.onreadystatechange=null,a.parentNode&&!b.debug&&k.removeChild(a),a=void 0,c())}}function c(b,c){i||q?(a.log("Start poll to fetch css"),setTimeout(function(){d(b,c)},1)):b.onload=b.onerror=function(){b.onload=
b.onerror=null;b=void 0;c()}}function d(a,b){var c;if(i)a.sheet&&(c=!0);else if(a.sheet)try{a.sheet.cssRules&&(c=!0)}catch(f){"NS_ERROR_DOM_SECURITY_ERR"===f.name&&(c=!0)}setTimeout(function(){c?b():d(a,b)},1)}function l(){}var n=document,k=n.head||n.getElementsByTagName("head")[0]||n.documentElement,g=k.getElementsByTagName("base")[0],p=/\.css(?:\?|$)/i,o=/loaded|complete|undefined/,f,h;a.fetch=function(b,d,i){var j=p.test(b),h=document.createElement(j?"link":"script");i&&(i=a.isFunction(i)?i(b):
i)&&(h.charset=i);d=d||l;"SCRIPT"===h.nodeName?e(h,d):c(h,d);j?(h.rel="stylesheet",h.href=b):(h.async="async",h.src=b);f=h;g?k.insertBefore(h,g):k.appendChild(h);f=null};a.getCurrentScript=function(){if(f)return f;if(h&&"interactive"===h.readyState)return h;for(var a=k.getElementsByTagName("script"),b=0;b<a.length;b++){var c=a[b];if("interactive"===c.readyState)return h=c}};a.getScriptAbsoluteSrc=function(a){return a.hasAttribute?a.src:a.getAttribute("src",4)};a.importStyle=function(a,b){if(!b||!n.getElementById(b)){var c=
n.createElement("style");b&&(c.id=b);k.appendChild(c);c.styleSheet?c.styleSheet.cssText=a:c.appendChild(n.createTextNode(a))}};var j=navigator.userAgent,i=536>Number(j.replace(/.*AppleWebKit\/(\d+)\..*/,"$1")),q=0<j.indexOf("Firefox")&&!("onload"in document.createElement("link"))}(seajs._util,seajs._config,this),function(a){var b=/(?:^|[^.$])\brequire\s*\(\s*(["'])([^"'\s\)]+)\1\s*\)/g;a.parseDependencies=function(e){var c=[],d,e=e.replace(/^\s*\/\*[\s\S]*?\*\/\s*$/mg,"").replace(/^\s*\/\/.*$/mg,
"");for(b.lastIndex=0;d=b.exec(e);)d[2]&&c.push(d[2]);return a.unique(c)}}(seajs._util),function(a,b,e){function c(a,b){this.uri=a;this.status=b||0}function d(a,f){return b.isString(a)?c._resolve(a,f):b.map(a,function(a){return d(a,f)})}function l(a,d){var m=b.parseMap(a);x[m]?(f[a]=f[m],d()):q[m]?r[m].push(d):(q[m]=!0,r[m]=[d],c._fetch(m,function(){x[m]=!0;var c=f[a];c.status===i.FETCHING&&(c.status=i.FETCHED);t&&(n(a,t),t=null);s&&c.status===i.FETCHED&&(f[a]=s,s.realUri=a);s=null;q[m]&&delete q[m];
r[m]&&(b.forEach(r[m],function(a){a()}),delete r[m])},e.charset))}function n(a,w){var m=f[a]||(f[a]=new c(a));m.status<i.SAVED&&(m.id=w.id||a,m.dependencies=d(b.filter(w.dependencies||[],function(a){return!!a}),a),m.factory=w.factory,m.status=i.SAVED);return m}function k(a,b){var c=a(b.require,b.exports,b);void 0!==c&&(b.exports=c)}function g(a){var c=a.realUri||a.uri,d=h[c];d&&(b.forEach(d,function(b){k(b,a)}),delete h[c])}function p(a){var c=a.uri;return b.filter(a.dependencies,function(a){u=[c];
if(a=o(f[a],c))u.push(c),b.log("Found circular dependencies:",u.join(" --\> "),void 0);return!a})}function o(a,c){if(!a||a.status!==i.SAVED)return!1;u.push(a.uri);var d=a.dependencies;if(d.length){if(-1<b.indexOf(d,c))return!0;for(var e=0;e<d.length;e++)if(o(f[d[e]],c))return!0}return!1}var f={},h={},j=[],i={FETCHING:1,FETCHED:2,SAVED:3,READY:4,COMPILING:5,COMPILED:6};c.prototype._use=function(a,c){b.isString(a)&&(a=[a]);var e=d(a,this.uri);this._load(e,function(){var a=b.map(e,function(a){return a?
f[a]._compile():null});c&&c.apply(null,a)})};c.prototype._load=function(a,d){function e(a){(a||{}).status<i.READY&&(a.status=i.READY);0===--j&&d()}var g=b.filter(a,function(a){return a&&(!f[a]||f[a].status<i.READY)}),h=g.length;if(0===h)d();else for(var j=h,k=0;k<h;k++)(function(a){function d(){g=f[a];if(g.status>=i.SAVED){var h=p(g);h.length?c.prototype._load(h,function(){e(g)}):e(g)}else b.log("It is not a valid CMD module: "+a),e()}var g=f[a]||(f[a]=new c(a,i.FETCHING));g.status>=i.FETCHED?d():
l(a,d)})(g[k])};c.prototype._compile=function(){function a(b){b=d(b,c.uri);b=f[b];if(!b)return null;if(b.status===i.COMPILING)return b.exports;b.parent=c;return b._compile()}var c=this;if(c.status===i.COMPILED)return c.exports;if(c.status<i.READY&&!h[c.realUri||c.uri])return null;c.status=i.COMPILING;a.async=function(a,b){c._use(a,b)};a.resolve=function(a){return d(a,c.uri)};a.cache=f;c.require=a;c.exports={};var e=c.factory;b.isFunction(e)?(j.push(c),k(e,c),j.pop()):void 0!==e&&(c.exports=e);c.status=
i.COMPILED;g(c);return c.exports};c._define=function(a,c,e){var g=arguments.length;1===g?(e=a,a=void 0):2===g&&(e=c,c=void 0,b.isArray(a)&&(c=a,a=void 0));!b.isArray(c)&&b.isFunction(e)&&(c=b.parseDependencies(e.toString()));var g={id:a,dependencies:c,factory:e},h;if(document.attachEvent){var j=b.getCurrentScript();j&&(h=b.unParseMap(b.getScriptAbsoluteSrc(j)));h||b.log("Failed to derive URI from interactive script for:",e.toString(),"warn")}if(j=a?d(a):h){if(j===h){var k=f[h];k&&(k.realUri&&k.status===
i.SAVED)&&(f[h]=null)}g=n(j,g);if(h){if((f[h]||{}).status===i.FETCHING)f[h]=g,g.realUri=h}else s||(s=g)}else t=g};c._getCompilingModule=function(){return j[j.length-1]};c._find=function(a){var c=[];b.forEach(b.keys(f),function(d){if(b.isString(a)&&-1<d.indexOf(a)||b.isRegExp(a)&&a.test(d))d=f[d],d.exports&&c.push(d.exports)});return c};c._modify=function(c,b){var e=d(c),g=f[e];g&&g.status===i.COMPILED?k(b,g):(h[e]||(h[e]=[]),h[e].push(b));return a};c.STATUS=i;c._resolve=b.id2Uri;c._fetch=b.fetch;
c.cache=f;var q={},x={},r={},t=null,s=null,u=[],v=new c(b.pageUri,i.COMPILED);a.use=function(c,b){var d=e.preload;d.length?v._use(d,function(){e.preload=[];v._use(c,b)}):v._use(c,b);return a};a.define=c._define;a.cache=c.cache;a.find=c._find;a.modify=c._modify;a.pluginSDK={Module:c,util:b,config:e}}(seajs,seajs._util,seajs._config),function(a,b,e){var c="seajs-ts="+b.now(),d=document.getElementById("seajsnode");d||(d=document.getElementsByTagName("script"),d=d[d.length-1]);var l=b.getScriptAbsoluteSrc(d)||
b.pageUri,l=b.dirname(function(a){if(a.indexOf("??")===-1)return a;var c=a.split("??"),a=c[0],c=b.filter(c[1].split(","),function(a){return a.indexOf("sea.js")!==-1});return a+c[0]}(l));b.loaderDir=l;var n=l.match(/^(.+\/)seajs\/[\d\.]+\/$/);n&&(l=n[1]);e.base=l;if(d=d.getAttribute("data-main"))e.main=d;e.charset="utf-8";a.config=function(d){for(var g in d)if(d.hasOwnProperty(g)){var p=e[g],o=d[g];if(p&&g==="alias")for(var f in o){if(o.hasOwnProperty(f)){var h=p[f],j=o[f];/^\d+\.\d+\.\d+$/.test(j)&&
(j=f+"/"+j+"/"+f);h&&h!==j&&b.log("The alias config is conflicted:","key =",'"'+f+'"',"previous =",'"'+h+'"',"current =",'"'+j+'"',"warn");p[f]=j}}else if(p&&(g==="map"||g==="preload")){b.isString(o)&&(o=[o]);b.forEach(o,function(a){a&&p.push(a)})}else e[g]=o}if((d=e.base)&&!b.isAbsolute(d))e.base=b.id2Uri((b.isRoot(d)?"":"./")+d+"/");if(e.debug===2){e.debug=1;a.config({map:[[/^.*$/,function(a){a.indexOf("seajs-ts=")===-1&&(a=a+((a.indexOf("?")===-1?"?":"&")+c));return a}]]})}if(e.debug)a.debug=!!e.debug;
return this};e.debug&&(a.debug=!!e.debug)}(seajs,seajs._util,seajs._config),function(a,b,e){a.log=b.log;a.importStyle=b.importStyle;a.config({alias:{seajs:b.loaderDir}});b.forEach(function(){var a=[],d=e.location.search,d=d.replace(/(seajs-\w+)(&|$)/g,"$1=1$2"),d=d+(" "+document.cookie);d.replace(/seajs-(\w+)=[1-9]/g,function(b,d){a.push(d)});return b.unique(a)}(),function(c){a.use("seajs/plugin-"+c);"debug"===c&&(a._use=a.use,a._useArgs=[],a.use=function(){a._useArgs.push(arguments);return a})})}(seajs,
seajs._util,this),function(a,b,e){var c=a._seajs;if(c&&!c.args)e.seajs=a._seajs;else{e.define=a.define;b.main&&a.use(b.main);if(b=(c||0).args)for(var c={"0":"config",1:"use",2:"define"},d=0;d<b.length;d+=2)a[c[b[d]]].apply(a,b[d+1]);e.define.cmd={};delete a.define;delete a._util;delete a._config;delete a._seajs}}(seajs,seajs._config,this),function(a,b){b.Qiyi=b.Qiyi||{};var e=b.Q;b.Q=b.Qiyi;var c,d,l=window.location.protocol;Qiyi.noConflict=function(){b.Q=e};Qiyi.ready=function(a){d=Q.liburl||l+"//static.iqiyi.com/js/lib/lib";
seajs.use(d,a||function(){})};Qiyi.PageInfo={};Qiyi.load=function(a){var b=Qiyi.projectName||"";c=Q.verurl||l+"//static.iqiyi.com/js/"+Qiyi.projectName+"/ver.js";if(!b)throw Error("\u672a\u6307\u5b9aprojectName");seajs.config({base:l+"//static.iqiyi.com/js/"+b});Qiyi.ready(function(){seajs.use(c,function(b){b.loadJob(a,function(a){a&&a.addJobs&&a.addJobs();a&&a.start&&a.start()})})})};window.addEventListener?window.addEventListener("load",function(){Qiyi.isWindowLoaded=!0},!1):window.attachEvent&&
window.attachEvent("onload",function(){Qiyi.isWindowLoaded=!0});var n=function(a){for(var a=a.split(";"),b=a.length,c={},d=0,e,j;d<b;d++)a[d]&&(j=a[d].split(":"),e=j[0],j=j[1],c[e]=j);return c},k=function(){function a(){if(!a.isReady){a.isReady=!0;for(var b=0,c=d.length;b<c;b++)d[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(c){setTimeout(b,1);return}a()}var c=!1,d=[],e;document.addEventListener?e=function(){document.removeEventListener("DOMContentLoaded",e,!1);a()}:document.attachEvent&&
(e=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",e),a())});(function(){if(!c)if(c=!0,"complete"===document.readyState)a.isReady=!0;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",e,!1),window.addEventListener("load",a,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",e);window.attachEvent("onload",a);var d=!1;try{d=null==window.frameElement}catch(f){}document.documentElement.doScroll&&d&&b()}})();return function(b){a.isReady?
b():d.push(b)}}();k.isReady=!1;k(function(){Q.ready(function(){var a=Qiyi.$("[data-widget]");a&&a.forEach(function(a){var a=Qiyi.$(a),b=a.attr("data-widget"),d=a.attr("data-async");try{var e=n(d)}catch(g){return!1}if("ready"==e.type)seajs.use(c,function(a){a.loadModule(b,function(){})});else if("load"==e.type)if(Qiyi.isWindowLoaded)seajs.use(c,function(a){a.loadModule(b,function(){})});else Qiyi.$(window).on("load",function(){seajs.use(c,function(a){a.loadModule(b,function(){})})});else if("trigger"==
e.type){var d=e.triggertype||"event",i=e.trigger;if("event"==d){var k=function(d){seajs.use(c,function(c){c.loadModule(b,function(b){a.un(i,k);b.trigger&&b.trigger(d)})})};a.on(i,k)}else if("lazyload"==d){var l=function(){seajs.use(c,function(a){a.loadModule(b,function(){Qiyi.$(window).un("scroll",r);Qiyi.$(window).un("resize",r)})})},r=function(){a.isInScreen()&&"inscreen"==i?l():!a.isInScreen()&&"outofscreen"==i&&l()};Qiyi.$(window).on("scroll",r);Qiyi.$(window).on("resize",r)}}})})})}(seajs,this));
